// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-vwKT_nnbFT1UQykpw7e6VqLSeUVBkTc',
    appId: '1:73208499391:web:163c48e0ac931a0f644a0a',
    messagingSenderId: '73208499391',
    projectId: 'ewan-geniuses',
    authDomain: 'ewan-geniuses.firebaseapp.com',
    storageBucket: 'ewan-geniuses.firebasestorage.app',
    measurementId: 'G-GFJFKNEY45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIyyT4bzx7svwpSEb-5LSNWyMJKMDMgVE',
    appId: '1:73208499391:android:80e6b17ad3f5b2ad644a0a',
    messagingSenderId: '73208499391',
    projectId: 'ewan-geniuses',
    storageBucket: 'ewan-geniuses.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSZAxxmFhFm16nFxuk7_ArxQUnGhjmrSM',
    appId: '1:73208499391:ios:9eab7d0e8c5f0f10644a0a',
    messagingSenderId: '73208499391',
    projectId: 'ewan-geniuses',
    storageBucket: 'ewan-geniuses.firebasestorage.app',
    iosBundleId: 'com.example.ewanMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSZAxxmFhFm16nFxuk7_ArxQUnGhjmrSM',
    appId: '1:73208499391:ios:9eab7d0e8c5f0f10644a0a',
    messagingSenderId: '73208499391',
    projectId: 'ewan-geniuses',
    storageBucket: 'ewan-geniuses.firebasestorage.app',
    iosBundleId: 'com.example.ewanMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-vwKT_nnbFT1UQykpw7e6VqLSeUVBkTc',
    appId: '1:73208499391:web:163c48e0ac931a0f644a0a',
    messagingSenderId: '73208499391',
    projectId: 'ewan-geniuses',
    authDomain: 'ewan-geniuses.firebaseapp.com',
    storageBucket: 'ewan-geniuses.firebasestorage.app',
    measurementId: 'G-GFJFKNEY45',
  );

}