import 'package:geniuses_school/presentation/widgets/teacher_orders/models/order_request_model.dart';
import 'package:flutter/material.dart';

import '../../../../l10n/app_localizations.dart';

final List<OrderRequest> Function(BuildContext) getDummyOrders =
    (BuildContext context) {
      final l10n = AppLocalizations.of(context)!;
      return [
        OrderRequest(
          id: '1',
          subject: l10n.subjectMathAlgebra,
          studentName: 'أحمد محمد علي',
          date: '2024-01-20',
          description: l10n.descMathAlgebra,
          price: '150',
          status: RequestStatus.pending,
          level: l10n.levelSecondary,
          lessonType: l10n.lessonTypeInPerson,
        ),
        OrderRequest(
          id: '2',
          subject: l10n.subjectPhysicsMechanics,
          studentName: 'فاطمة حسن',
          date: '2024-01-19',
          description: l10n.descPhysicsMechanics,
          price: '200',
          status: RequestStatus.urgent,
          level: l10n.levelSecondary,
          lessonType: l10n.lessonTypeOnline,
        ),
        OrderRequest(
          id: '3',
          subject: l10n.subjectOrganicChemistry,
          studentName: 'سارة أحمد',
          date: '2024-01-18',
          description: l10n.descOrganicChemistry,
          price: '180',
          status: RequestStatus.accepted,
          level: l10n.levelSecondary,
          lessonType: l10n.lessonTypeOnline,
        ),
        OrderRequest(
          id: '4',
          subject: l10n.subjectEnglishGrammar,
          studentName: 'محمد حسن',
          date: '2024-01-15',
          description: l10n.descEnglishGrammar,
          price: '120',
          status: RequestStatus.completed,
          level: l10n.levelIntermediate,
          lessonType: l10n.lessonTypeInPerson,
        ),
        OrderRequest(
          id: '5',
          subject: l10n.subjectBiologyGenetics,
          studentName: 'نور الدين',
          date: '2024-01-21',
          description: l10n.descBiologyGenetics,
          price: '160',
          status: RequestStatus.pending,
          level: l10n.levelSecondary,
          lessonType: l10n.lessonTypeOnline,
        ),
        OrderRequest(
          id: '6',
          subject: l10n.subjectMathStatistics,
          studentName: 'ريم عبدالله',
          date: '2024-01-17',
          description: l10n.descMathStatistics,
          price: '140',
          status: RequestStatus.accepted,
          level: l10n.levelUniversity,
          lessonType: l10n.lessonTypeInPerson,
        ),
        OrderRequest(
          id: '7',
          subject: l10n.subjectPhysicsElectricity,
          studentName: 'خالد محمود',
          date: '2024-01-22',
          description: l10n.descPhysicsElectricity,
          price: '190',
          status: RequestStatus.urgent,
          level: l10n.levelSecondary,
          lessonType: l10n.lessonTypeOnline,
        ),
        OrderRequest(
          id: '8',
          subject: l10n.subjectProgrammingPython,
          studentName: 'عمر سعيد',
          date: '2024-01-14',
          description: l10n.descProgrammingPython,
          price: '200',
          status: RequestStatus.completed,
          level: l10n.levelUniversity,
          lessonType: l10n.lessonTypeOnline,
        ),
        OrderRequest(
          id: '9',
          subject: l10n.subjectArabicGrammar,
          studentName: 'ليلى أحمد',
          date: '2024-01-23',
          description: l10n.descArabicGrammar,
          price: '130',
          status: RequestStatus.pending,
          level: l10n.levelIntermediate,
          lessonType: l10n.lessonTypeInPerson,
        ),
        OrderRequest(
          id: '10',
          subject: l10n.subjectGeography,
          studentName: 'يوسف علي',
          date: '2024-01-16',
          description: l10n.descGeography,
          price: '110',
          status: RequestStatus.accepted,
          level: l10n.levelIntermediate,
          lessonType: l10n.lessonTypeInPerson,
        ),
      ];
    };
